### ISSUE TITLE
Regarding production version

### ISSUE THREAD

**Issue by kunjee17** [keithf4/pg_doc_store#3]
First of all thanks for your effort to make this plugin less. I like databases and they are awesome in what they do. But I am more server language person. 

I love when first time Rob coin the term SQL and NoSQL together in project, around 2011 I guess. And Postgres exactly giving that without without using two technology. 

So, here are few questions if you don't mind. 
1. Can I use your version at [Elephant SQL](https://www.elephantsql.com/). As I said I don't want to manager things and go fast without migration issues. I asked this because I don't know third party is allowed on above cloud server. (If you have any other alternative who can host my db in azure or outside and also cheap, includes plugins will love to know that.)
1. You said it is not production ready? So, are you still working on this? So, should I try Rob's version. 

Any suggestion for moving fast without having migration (as problem) are always welcome.

Thanks. 

PS: You can close the issue if you want as this is not really issue with library but I don't know where to ask question to I find issues more suitable place.

**Comment by keithf4** [comment]
I'm not familiar with Elephant SQL, but if it's like Amazon RDS, third party extensions may not be supported easily. Since it's just plain plpgsql, you could probably do a find/replace on the @extschema@ macro and it may install fine by just running it as a plain sql file. But then trying to maintain any updates going forward would be really challenging since you have no reliable way to know what version is installed.

If you really want to be able to run third-party postgresql extensions, I'd say avoid the database-as-a-service model entirely. I don't know of any of those that allow plugins other than what they support themselves. I'd recommend getting a normal server (either bare-metal or a VM like Amazon EC2 or Digital Ocean) which you then install postgresql on yourself. You have to manage a lot more yourself (slaves/failover/backup) but you get the flexibility of running things exactly how you need.

I say it's not production ready because I just did this as a side project to learn json and it's not something I'm actively using anywhere currently. The UPSERT feature in 9.5 would also make this much more reliable, but I don't currently have the time to work on it. If you'd like to sponsor any development on this, feel free to contact my employer and we could probably work something out (omniti.com).

**Comment by kunjee17** [comment]
@keithf4 I think I got your point. Postgresql is having power in his extensions and it would be better if I do little maintenance by self and can have all the power of extensions. 

Thanks for detailed reply. 

I m closing comment for now.
